#!/usr/bin/env ruby

require_relative 'sleepy_worker'
require 'sidekiq/api'

JOB_SLEEP = 20

def log(msg)
  puts "REPRODUCE LOG: #{msg}"
end

log 'Reproducing the bug'

log '1. Starting Sidekiq and waiting 5s'
sidekiq_pid = spawn('sidekiq -c1 -r ./sidekiq.rb')
sleep 5

log "Jobs in the default queue: #{Sidekiq::Queue.new.size}"
log "Job in progress: #{Sidekiq::Workers.new.size}"

log '2. Enqueueing a batch and waiting 5s'
batch = Sidekiq::Batch.new
batch.jobs { SleepyWorker.perform_async(sleep: JOB_SLEEP) }
bid = batch.bid
sleep 5

log "Jobs in the default queue: #{Sidekiq::Queue.new.size}"
log "Job in progress: #{Sidekiq::Workers.new.size}"
log "Jobs pending in batch: #{Sidekiq::Batch::Status.new(bid).pending}"

log '3. Sending SIGINT to Sidekiq'
Process.kill('INT', sidekiq_pid)
sleep 0.5

# If this happened after you see "Bye!" then reproduce will not work.
log '4. Sending SIGKILL to Sidekiq too soon'
Process.kill('KILL', sidekiq_pid)
sleep 3

log "Jobs in the default queue: #{Sidekiq::Queue.new.size}"
log "Job in progress: #{Sidekiq::Workers.new.size}"
log "Jobs pending in batch: #{Sidekiq::Batch::Status.new(bid).pending}"

log '5. Starting Sidekiq again and waiting 3s'
sidekiq_pid = spawn('sidekiq -c1 -r ./sidekiq.rb')
sleep 3

log "Waiting #{JOB_SLEEP + 5}s for the job to finish."
sleep JOB_SLEEP + 5

pending_size = Sidekiq::Batch::Status.new(bid).pending

if pending_size > 0
  log "Jobs in the default queue: #{Sidekiq::Queue.new.size}"
  log "Job in progress: #{Sidekiq::Workers.new.size}"
  log "Jobs pending in batch: #{pending_size}"
  log "Expected batch to complete, but still pending with #{pending_size} jobs"
else
  log "Reproduce didn't work. Run the script again."
end

log 'Killing sidekiq'
Process.kill('KILL', sidekiq_pid)
sleep 3
